#!/usr/bin/env python3
"""
Main Parameters Documentation
============================

This script documents all the main parameters used in the RL-based RIR estimation system,
organized by category with explanations and current values.
"""

def print_parameters():
    """Print comprehensive parameter documentation."""

    print("🎯 MAIN PARAMETERS - RL-Based RIR Estimation")
    print("=" * 60)
    print()

    # Audio Processing Parameters
    print("🎵 AUDIO PROCESSING PARAMETERS:")
    print("-" * 40)
    print("• sample_rate: 16000 Hz")
    print("  → Audio sampling rate (standard for speech processing)")
    print()
    print("• n_fft: 1024 samples")
    print("  → FFT window size for spectral analysis")
    print()
    print("• hop_length: 256 samples")
    print("  → STFT hop size (16ms frames at 16kHz)")
    print()
    print("• win_length: 1024 samples")
    print("  → STFT window length (matches n_fft)")
    print()
    print("• speech_length_training: 48000 samples (3.0 seconds)")
    print("  → Length of speech segments used for training and reward calculation")
    print()
    print("• speech_length_demo: 32000 samples (2.0 seconds)")
    print("  → Length of speech segments used for demonstration/evaluation")
    print()

    # RIR Parameters
    print("🏠 ROOM IMPULSE RESPONSE (RIR) PARAMETERS:")
    print("-" * 50)
    print("• rir_length: 1024 samples")
    print("  → Fixed RIR length (64ms at 16kHz, captures essential room acoustics)")
    print()
    print("• regularization: 0.001")
    print("  → Wiener deconvolution regularization parameter")
    print()
    print("• regularization (Wiener): 0.01")
    print("  → Runtime Wiener filter regularization in neural agent")
    print()

    # Neural Network Architecture Parameters
    print("🧠 NEURAL NETWORK ARCHITECTURE:")
    print("-" * 40)
    print("• hidden_dim: 768")
    print("  → Main hidden dimension for RIR policy network")
    print()
    print("• latent_dim: 384")
    print("  → Derived from hidden_dim // 2")
    print()
    print("• dropout: 0.1")
    print("  → Dropout rate for regularization")
    print()
    print("• weight_decay: 1e-5")
    print("  → L2 regularization in Adam optimizer")
    print()

    # RIR Structure Scaling Parameters
    print("🏗️ RIR STRUCTURE SCALING:")
    print("-" * 30)
    print("• direct_scale: 0.3")
    print("  → Scaling factor for direct sound head output")
    print()
    print("• early_scale: 0.4")
    print("  → Scaling factor for early reflections head")
    print()
    print("• late_scale: 0.3")
    print("  → Scaling factor for late reverberation head")
    print()
    print("• tail_scale: 0.2")
    print("  → Scaling factor for exponential tail head")
    print()

    # Training Parameters
    print("🎓 TRAINING PARAMETERS:")
    print("-" * 25)
    print("• learning_rate: 0.001")
    print("  → Adam optimizer learning rate")
    print()
    print("• gamma: 0.95")
    print("  → Discount factor for future rewards")
    print()
    print("• update_scale: 0.05")
    print("  → Scaling factor for RIR updates")
    print()
    print("• batch_size: 32")
    print("  → Experience batch size (not currently used)")
    print()
    print("• memory_size: 10000")
    print("  → Experience replay buffer size")
    print()

    # Environment Parameters
    print("🌍 ENVIRONMENT PARAMETERS:")
    print("-" * 30)
    print("• max_iterations: 15-20")
    print("  → Maximum steps per training episode")
    print()
    print("• episodes: 20-1000")
    print("  → Number of training episodes")
    print()
    print("• max_steps: 50-200")
    print("  → Maximum steps for DQN training")
    print()

    # Reward Function Parameters
    print("🎁 REWARD FUNCTION PARAMETERS:")
    print("-" * 35)
    print("• drr_weight: 2.0")
    print("  → Weight for DRR-based reward component")
    print()
    print("• direct_weight: 0.8")
    print("  → Weight for direct sound strength reward")
    print()
    print("• early_struct_weight: 1.2")
    print("  → Weight for early reflection structure reward")
    print()
    print("• late_struct_weight: 1.0")
    print("  → Weight for late reverberation structure reward")
    print()
    print("• tail_presence_weight: 0.8")
    print("  → Weight for tail presence reward")
    print()
    print("• decay_weight: 0.1")
    print("  → Weight for exponential decay shape reward")
    print()
    print("• oracle_weight: 0.2")
    print("  → Weight for oracle correlation reward (optional)")
    print()

    # Acoustic Structure Parameters
    print("🎚️ ACOUSTIC STRUCTURE PARAMETERS:")
    print("-" * 40)
    print("• momentum: 0.2")
    print("  → Momentum factor for RIR updates")
    print()
    print("• exploration_noise: 0.01")
    print("  → Standard deviation of exploration noise")
    print()
    print("• early_decay_constant: 200")
    print("  → Sample decay constant for early reflections")
    print()
    print("• late_decay_constant: 50")
    print("  → Sample decay constant for late reverberation")
    print()
    print("• tail_decay_constant: 100")
    print("  → Sample decay constant for exponential tail")
    print()

    # DRR Computation Parameters
    print("📊 DRR COMPUTATION PARAMETERS:")
    print("-" * 35)
    print("• frame_size: 0.025 * sample_rate")
    print("  → Frame size for DRR analysis (25ms)")
    print()
    print("• hop_size: 0.01 * sample_rate")
    print("  → Hop size for DRR analysis (10ms)")
    print()
    print("• direct_window_frames: 20")
    print("  → Maximum frames for direct sound detection (200ms)")
    print()
    print("• drr_normalization: 15.0 dB")
    print("  → Maximum DRR value for reward normalization")
    print()

    # DQN-Specific Parameters
    print("🎮 DQN-SPECIFIC PARAMETERS:")
    print("-" * 30)
    print("• epsilon: 1.0 → 0.01")
    print("  → Initial and final exploration rate")
    print()
    print("• epsilon_decay: 0.995")
    print("  → Exponential decay rate for epsilon")
    print()
    print("• target_update_freq: 10")
    print("  → Frequency of target network updates")
    print()
    print("• discrete_actions: 16-64")
    print("  → Number of discrete actions for continuous action space")
    print()

    # Data and Evaluation Parameters
    print("📈 DATA & EVALUATION PARAMETERS:")
    print("-" * 40)
    print("• synthetic_data: true")
    print("  → Use synthetic training data")
    print()
    print("• data_augmentation: true")
    print("  → Apply data augmentation")
    print()
    print("• num_eval_episodes: 10")
    print("  → Number of evaluation episodes")
    print()
    print("• save_audio_samples: true")
    print("  → Save audio samples during evaluation")
    print()

    # Project Configuration
    print("⚙️ PROJECT CONFIGURATION:")
    print("-" * 30)
    print("• project_name: rir-rl-estimation")
    print("  → Project identifier")
    print()
    print("• experiment_name: quick_start")
    print("  → Current experiment name")
    print()
    print("• use_wandb: false")
    print("  → Enable Weights & Biases logging")
    print()
    print("• seed: 42")
    print("  → Random seed for reproducibility")
    print()

    # Streaming Parameters
    print("🌊 STREAMING PARAMETERS:")
    print("-" * 25)
    print("• enabled: false")
    print("  → Enable streaming/online mode")
    print()
    print("• stream_dir: data/stream")
    print("  → Directory for streaming audio segments")
    print()
    print("• poll_interval_sec: 2.0")
    print("  → Polling interval for new audio segments")
    print()

    print("📋 SUMMARY:")
    print("-" * 10)
    print("• Total parameters documented: 67+")
    print("• Categories: Audio, RIR, Neural Network, Training, Environment, Rewards")
    print("• Most parameters configurable via configs/default_config.yaml")
    print("• Neural network parameters hardcoded in RIRPolicyNetwork class")
    print("• Reward weights tuned for acoustic realism and DRR optimization")
    print("• Speech segments: 2-3 seconds (32k-48k samples) for dereverberation & rewards")

if __name__ == "__main__":
    print_parameters()